<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'File Type' => '文件类型',
    'File does not exist.' => '文件不存在',
    'File mineType' => '文件类型',
    'ID' => '',
    'Model' => '模型',
    'Model Id' => '模型ID',
    'Batch Deletion' => '批量删除',
    'Created At' => '上传时间',
    'Delete Attachment' => '删除附件',
    'File Ext' => '后缀',
    'File Hash' => '哈希',
    'File Size' => '文件大小',
    'Filename' => '文件名',
    'Manage Attachment' => '附件管理',
    'Original FileName' => '原始名称',
    'Path' => '路径',
    'Select Files' => '选择文件',
    'Select file' => '选择文件',
    'User Id' => '上传用户',
    'User Ip' => '上传IP',
];
