<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'File Allow Files' => '允许的文件后缀',
    'File Max Size' => '文件大小',
    'ID' => '',
    'Image Allow Files' => '允许的图片后缀',
    'Image Max Size' => '图片大小',
    'Settings' => '设置',
    'Storage Url' => '访问Url',
    'Store Path' => '存储路径',
    'Video Allow Files' => '允许的视频后缀',
    'Video Max Size' => '视频大小',
    'An error occurred while saving the file.' => '文件保存时出错',
    'Batch Deletion' => '批量删除',
    'Created At' => '上传时间',
    'Delete Attachment' => '删除附件',
    'File Size' => '文件大小',
    'File Type' => '文件类型',
    'File Upload' => '文件上传',
    'Filename' => '文件名',
    'Manage Attachment' => '附件管理',
    'Original FileName' => '原始名称',
    'Path' => '路径',
    'Select Files' => '选择文件',
    'The file size exceeds the site limit.' => '文件大小超出网站限制',
    'The link contentType is incorrect.' => '链接contentType不正确',
    'The link is not an http link.' => '链接不是http链接',
    'The link is not available.' => '该链接不可达。',
    'User Id' => '上传用户',
    'User Ip' => '上传IP',
];
